# Generated by Django 5.0.6 on 2024-07-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrito_id', models.IntegerField()),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
